apiVersion : apps/v1
kind: Deployment
metadata:
  name: grpcserver 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpcserver 
    spec:
      containers:
        - name: grpcserver 
          image: oapidemoacr.azurecr.io/grpcserver
          ports:
          - containerPort: 80